import type { Publicacion } from "./types"

const now = Date.now()
const toDate = (hoursAgo: number) => new Date(now - hoursAgo * 60 * 60 * 1000)

export const mockPublicaciones: Publicacion[] = [
    // ---------------------------------------------------------
    // 10 MASCOTAS PERDIDAS
    // ---------------------------------------------------------
    {
        id: "mock-perdida-1",
        tipoPublicacion: "perdida",
        mascota: {
            id: "mock-pet-p1",
            especie: "perro",
            raza: "golden",
            sexo: "macho",
            color: "Dorado",
            descripcion: "Golden simpático perdido con collar rojo. Tiene una mancha blanca en la pata.",
            imagenUrl: "https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=600&h=600&fit=crop",
        },
        ubicacion: "Palermo Soho",
        fechaPublicacion: toDate(2),
        fechaEncuentro: toDate(4),
        contactoNombre: "Juan P.",
        contactoTelefono: "1144556677",
        contactoEmail: "juan@test.com",
        mostrarContactoPublico: true,
        usuarioId: "user-test",
        activa: true,
        esPrueba: true,
        transitoUrgente: true,
    },
    {
        id: "mock-perdida-2",
        tipoPublicacion: "perdida",
        mascota: {
            id: "mock-pet-p2",
            especie: "gato",
            raza: "siames",
            sexo: "hembra",
            color: "Beige y negro",
            descripcion: "Gatita muy asustada, se escondió debajo de un auto.",
            imagenUrl: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&h=600&fit=crop",
        },
        ubicacion: "Recoleta",
        fechaPublicacion: toDate(5),
        fechaEncuentro: toDate(10),
        contactoNombre: "Maria G.",
        contactoTelefono: "1199887766",
        contactoEmail: "maria@test.com",
        mostrarContactoPublico: false,
        usuarioId: "user-test2",
        activa: true,
        esPrueba: true,
        transitoUrgente: false,
    },
    {
        id: "mock-perdida-3",
        tipoPublicacion: "perdida",
        mascota: {
            id: "mock-pet-p3",
            especie: "perro",
            raza: "mestizo_perro",
            sexo: "desconocido",
            color: "Negro",
            descripcion: "Perrito sin collar caminando desorientado por la avenida.",
            imagenUrl: "https://images.unsplash.com/photo-1477884213360-7e9d7dcc1e48?w=600&h=600&fit=crop",
        },
        ubicacion: "Caballito",
        fechaPublicacion: toDate(12),
        fechaEncuentro: toDate(24),
        contactoNombre: "Carlos R.",
        contactoTelefono: "1133221144",
        contactoEmail: "carlos@test.com",
        mostrarContactoPublico: true,
        usuarioId: "user-test3",
        activa: true,
        esPrueba: true,
        transitoUrgente: true,
    },
    {
        id: "mock-perdida-4",
        tipoPublicacion: "perdida",
        mascota: {
            id: "mock-pet-p4",
            especie: "otro",
            raza: "otra",
            sexo: "macho",
            color: "Verde",
            descripcion: "Al parecer es una cotorra o loro perdido. Se posó en mi ventana.",
            imagenUrl: "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=600&h=600&fit=crop",
        },
        ubicacion: "Belgrano",
        fechaPublicacion: toDate(20),
        fechaEncuentro: toDate(48),
        contactoNombre: "Ana S.",
        contactoTelefono: "1122334455",
        contactoEmail: "ana@test.com",
        mostrarContactoPublico: false,
        usuarioId: "user-test4",
        activa: true,
        esPrueba: true,
        transitoUrgente: false,
    },
    {
        id: "mock-perdida-5",
        tipoPublicacion: "perdida",
        mascota: {
            id: "mock-pet-p5",
            especie: "perro",
            raza: "bulldog",
            sexo: "macho",
            color: "Blanco y marrón",
            descripcion: "Bulldog francés gordito, no tiene identificador.",
            imagenUrl: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&h=600&fit=crop",
        },
        ubicacion: "Almagro",
        fechaPublicacion: toDate(22),
        fechaEncuentro: toDate(30),
        contactoNombre: "Luisa M.",
        contactoTelefono: "1155667788",
        contactoEmail: "luisa@test.com",
        mostrarContactoPublico: true,
        usuarioId: "user-test",
        activa: true,
        esPrueba: true,
        transitoUrgente: true,
    },
    {
        id: "mock-perdida-6",
        tipoPublicacion: "perdida",
        mascota: {
            id: "mock-pet-p6",
            especie: "gato",
            raza: "mestizo_gato",
            sexo: "macho",
            color: "Naranja",
            descripcion: "Gato atigrado naranja, muy mimoso, parece de casa.",
            imagenUrl: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&h=600&fit=crop",
        },
        ubicacion: "Villa Crespo",
        fechaPublicacion: toDate(25),
        fechaEncuentro: toDate(36),
        contactoNombre: "Martin O.",
        contactoTelefono: "1188990011",
        contactoEmail: "martin@test.com",
        mostrarContactoPublico: false,
        usuarioId: "user-test2",
        activa: true,
        esPrueba: true,
        transitoUrgente: false,
    },
    {
        id: "mock-perdida-7",
        tipoPublicacion: "perdida",
        mascota: {
            id: "mock-pet-p7",
            especie: "perro",
            raza: "caniche",
            sexo: "hembra",
            color: "Blanco",
            descripcion: "Caniche toy, con moño rosado. Lloraba en la puerta del super.",
            imagenUrl: "https://images.unsplash.com/photo-1596492784531-6e6eb5ea9993?w=600&h=600&fit=crop",
        },
        ubicacion: "Nuñez",
        fechaPublicacion: toDate(40),
        fechaEncuentro: toDate(50),
        contactoNombre: "Silvia T.",
        contactoTelefono: "1177665544",
        contactoEmail: "silvia@test.com",
        mostrarContactoPublico: true,
        usuarioId: "user-test",
        activa: true,
        esPrueba: true,
        transitoUrgente: true,
    },
    {
        id: "mock-perdida-8",
        tipoPublicacion: "perdida",
        mascota: {
            id: "mock-pet-p8",
            especie: "gato",
            raza: "persa",
            sexo: "desconocido",
            color: "Gris",
            descripcion: "Gato de pelo largo gris. Salió de un árbol.",
            imagenUrl: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=600&h=600&fit=crop",
        },
        ubicacion: "Colegiales",
        fechaPublicacion: toDate(45),
        fechaEncuentro: toDate(60),
        contactoNombre: "Oscar E.",
        contactoTelefono: "1144332211",
        contactoEmail: "oscar@test.com",
        mostrarContactoPublico: false,
        usuarioId: "user-test3",
        activa: true,
        esPrueba: true,
        transitoUrgente: false,
    },
    {
        id: "mock-perdida-9",
        tipoPublicacion: "perdida",
        mascota: {
            id: "mock-pet-p9",
            especie: "perro",
            raza: "pastor_aleman",
            sexo: "macho",
            color: "Negro y fuego",
            descripcion: "Pastor alemán adulto con doble collar. Algo cojo de la pata trasera.",
            imagenUrl: "https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=600&h=600&fit=crop",
        },
        ubicacion: "Saavedra",
        fechaPublicacion: toDate(70),
        fechaEncuentro: toDate(72),
        contactoNombre: "Fernando C.",
        contactoTelefono: "1199112233",
        contactoEmail: "fer@test.com",
        mostrarContactoPublico: true,
        usuarioId: "user-test2",
        activa: true,
        esPrueba: true,
        transitoUrgente: false,
    },
    {
        id: "mock-perdida-10",
        tipoPublicacion: "perdida",
        mascota: {
            id: "mock-pet-p10",
            especie: "otro",
            raza: "otra",
            sexo: "hembra",
            color: "Marrón",
            descripcion: "Hurón perdido, muy amistoso.",
            imagenUrl: "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=600&h=600&fit=crop",
        },
        ubicacion: "Villa Urquiza",
        fechaPublicacion: toDate(100),
        fechaEncuentro: toDate(120),
        contactoNombre: "Laura L.",
        contactoTelefono: "1188334466",
        contactoEmail: "laura@test.com",
        mostrarContactoPublico: true,
        usuarioId: "user-test",
        activa: true,
        esPrueba: true,
        transitoUrgente: true,
    },

    // ---------------------------------------------------------
    // 10 MASCOTAS EN ADOPCIÓN
    // ---------------------------------------------------------
    {
        id: "mock-adopcion-1",
        tipoPublicacion: "adopcion",
        mascota: {
            id: "mock-pet-a1",
            especie: "perro",
            raza: "mestizo_perro",
            sexo: "hembra",
            color: "Blanca con manchas negras",
            descripcion: "Rescatada de una autopista. Es súper dócil y se lleva bien con chicos. Lista para adoptar.",
            edad: "1 año",
            imagenUrl: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=600&h=600&fit=crop",
        },
        ubicacion: "San Telmo",
        fechaPublicacion: toDate(1),
        contactoNombre: "Refugio Patitas",
        contactoTelefono: "1155556666",
        contactoEmail: "contacto@patitas.org",
        mostrarContactoPublico: true,
        usuarioId: "refugio1",
        activa: true,
        esPrueba: true,
    },
    {
        id: "mock-adopcion-2",
        tipoPublicacion: "adopcion",
        mascota: {
            id: "mock-pet-a2",
            especie: "gato",
            raza: "mestizo_gato",
            sexo: "macho",
            color: "Gris atigrado",
            descripcion: "Es un terremoto encantador. Solo quiere jugar y dormir en el regazo de alguien.",
            edad: "4 meses",
            imagenUrl: "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=600&h=600&fit=crop",
        },
        ubicacion: "Flores",
        fechaPublicacion: toDate(6),
        contactoNombre: "Asociación Gatos Felices",
        contactoTelefono: "1122223333",
        contactoEmail: "info@gatosfelices.com",
        mostrarContactoPublico: false,
        usuarioId: "refugio2",
        activa: true,
        esPrueba: true,
    },
    {
        id: "mock-adopcion-3",
        tipoPublicacion: "adopcion",
        mascota: {
            id: "mock-pet-a3",
            especie: "perro",
            raza: "caniche",
            sexo: "macho",
            color: "Apricot",
            descripcion: "Perrito mayor que necesita una casa tranquila. Ideal para acompañar a una persona sola.",
            edad: "10 años",
            imagenUrl: "https://images.unsplash.com/photo-1596492784531-6e6eb5ea9993?w=600&h=600&fit=crop",
        },
        ubicacion: "Villa Devoto",
        fechaPublicacion: toDate(11),
        contactoNombre: "Marta R.",
        contactoTelefono: "1166667777",
        contactoEmail: "marta@test.com",
        mostrarContactoPublico: true,
        usuarioId: "user-test4",
        activa: true,
        esPrueba: true,
    },
    {
        id: "mock-adopcion-4",
        tipoPublicacion: "adopcion",
        mascota: {
            id: "mock-pet-a4",
            especie: "otro",
            raza: "otra",
            sexo: "hembra",
            color: "Blanco",
            descripcion: "Conejita rescatada, ya esterilizada. Come heno y hace pis en su litera.",
            edad: "1 año y medio",
            imagenUrl: "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=600&h=600&fit=crop",
        },
        ubicacion: "Mataderos",
        fechaPublicacion: toDate(15),
        contactoNombre: "Daniela L.",
        contactoTelefono: "1199990000",
        contactoEmail: "daniela@test.com",
        mostrarContactoPublico: false,
        usuarioId: "user-test",
        activa: true,
        esPrueba: true,
    },
    {
        id: "mock-adopcion-5",
        tipoPublicacion: "adopcion",
        mascota: {
            id: "mock-pet-a5",
            especie: "perro",
            raza: "labrador",
            sexo: "macho",
            color: "Negro",
            descripcion: "Cachorrón enorme, es muy bruto jugando, pero con un gran corazón. Requiere cuidado.",
            edad: "8 meses",
            imagenUrl: "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?w=600&h=600&fit=crop",
        },
        ubicacion: "Retiro",
        fechaPublicacion: toDate(24),
        contactoNombre: "Carlos D.",
        contactoTelefono: "1188887777",
        contactoEmail: "carlosd@test.com",
        mostrarContactoPublico: true,
        usuarioId: "user-test2",
        activa: true,
        esPrueba: true,
    },
    {
        id: "mock-adopcion-6",
        tipoPublicacion: "adopcion",
        mascota: {
            id: "mock-pet-a6",
            especie: "gato",
            raza: "maine_coon",
            sexo: "macho",
            color: "Pardo y blanco",
            descripcion: "Gato tamaño XXL. Su dueño original falleció y necesita reubicación. Muy cariñoso.",
            edad: "5 años",
            imagenUrl: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&h=600&fit=crop",
        },
        ubicacion: "San Nicolás",
        fechaPublicacion: toDate(32),
        contactoNombre: "Elena G.",
        contactoTelefono: "1155554444",
        contactoEmail: "elena@test.com",
        mostrarContactoPublico: false,
        usuarioId: "user-test3",
        activa: true,
        esPrueba: true,
    },
    {
        id: "mock-adopcion-7",
        tipoPublicacion: "adopcion",
        mascota: {
            id: "mock-pet-a7",
            especie: "perro",
            raza: "mestizo_perro",
            sexo: "hembra",
            color: "Marrón claro",
            descripcion: "Perrita rescatada de abandono. Es tímida al principio y busca una familia paciente.",
            edad: "2 años",
            imagenUrl: "https://images.unsplash.com/photo-1477884213360-7e9d7dcc1e48?w=600&h=600&fit=crop",
        },
        ubicacion: "Liniers",
        fechaPublicacion: toDate(48),
        contactoNombre: "Agrupación 4 Patas",
        contactoTelefono: "1133332222",
        contactoEmail: "contacto@4patas.com",
        mostrarContactoPublico: true,
        usuarioId: "refugio1",
        activa: true,
        esPrueba: true,
    },
    {
        id: "mock-adopcion-8",
        tipoPublicacion: "adopcion",
        mascota: {
            id: "mock-pet-a8",
            especie: "gato",
            raza: "comun_europeo",
            sexo: "hembra",
            color: "Carey",
            descripcion: "Gatita carey rescatada del puerto. Esterilizada y chipada. Tiene una personalidad única.",
            edad: "3 años",
            imagenUrl: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=600&h=600&fit=crop",
        },
        ubicacion: "La Boca",
        fechaPublicacion: toDate(55),
        contactoNombre: "Puerto Felino",
        contactoTelefono: "1144445555",
        contactoEmail: "info@puertofelino.com",
        mostrarContactoPublico: false,
        usuarioId: "refugio2",
        activa: true,
        esPrueba: true,
    },
    {
        id: "mock-adopcion-9",
        tipoPublicacion: "adopcion",
        mascota: {
            id: "mock-pet-a9",
            especie: "perro",
            raza: "beagle",
            sexo: "macho",
            color: "Tricolor",
            descripcion: "Encontrado amarrado en un parque, super energético y activo. Necesita patio.",
            edad: "1 año y medio",
            imagenUrl: "https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=600&h=600&fit=crop",
        },
        ubicacion: "Agronomía",
        fechaPublicacion: toDate(60),
        contactoNombre: "Pablo Z.",
        contactoTelefono: "1199991111",
        contactoEmail: "pablo@test.com",
        mostrarContactoPublico: true,
        usuarioId: "user-test",
        activa: true,
        esPrueba: true,
    },
    {
        id: "mock-adopcion-10",
        tipoPublicacion: "adopcion",
        mascota: {
            id: "mock-pet-a10",
            especie: "gato",
            raza: "mestizo_gato",
            sexo: "macho",
            color: "Blanco polar",
            descripcion: "Gato blanco esponjoso, requiere vacunas, pero está sano. Es sordo de nacimiento.",
            edad: "8 meses",
            imagenUrl: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&h=600&fit=crop",
        },
        ubicacion: "Chacarita",
        fechaPublicacion: toDate(65),
        contactoNombre: "Sofia R.",
        contactoTelefono: "1188882222",
        contactoEmail: "sofia@test.com",
        mostrarContactoPublico: false,
        usuarioId: "user-test2",
        activa: true,
        esPrueba: true,
    },
]
